"""Some fixes 2

Revision ID: 83a619eaf86d
Revises: 8669861d613f
Create Date: 2025-12-12 01:53:01.824835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a619eaf86d'
down_revision: Union[str, Sequence[str], None] = '8669861d613f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_part_id_fkey'), 'images', type_='foreignkey')
    op.drop_constraint(op.f('images_car_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'parts', ['part_id'], ['part_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'images', 'cars', ['car_id'], ['car_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('part_specifications_part_id_fkey'), 'part_specifications', type_='foreignkey')
    op.create_foreign_key(None, 'part_specifications', 'parts', ['part_id'], ['part_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'part_specifications', type_='foreignkey')
    op.create_foreign_key(op.f('part_specifications_part_id_fkey'), 'part_specifications', 'parts', ['part_id'], ['part_id'])
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_car_id_fkey'), 'images', 'cars', ['car_id'], ['car_id'])
    op.create_foreign_key(op.f('images_part_id_fkey'), 'images', 'parts', ['part_id'], ['part_id'])
    # ### end Alembic commands ###
