"""Some fixes

Revision ID: 8669861d613f
Revises: 39f5593d3d1c
Create Date: 2025-12-11 23:20:00.379501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8669861d613f'
down_revision: Union[str, Sequence[str], None] = '39f5593d3d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.drop_column('images', 'primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('primary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('images', 'sort_order')
    # ### end Alembic commands ###
