"""Create CarOrder and Settings tables and some fixes

Revision ID: aa35c0b40ccc
Revises: 2eab6562ed32
Create Date: 2025-12-20 22:18:31.658723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa35c0b40ccc'
down_revision: Union[str, Sequence[str], None] = '2eab6562ed32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_points',
    sa.Column('pickup_point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('house', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pickup_point_id')
    )
    op.create_table('settings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('car_orders',
    sa.Column('car_order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('car_order_id')
    )
    op.drop_constraint(op.f('cart_items_user_id_part_id_key'), 'cart_items', type_='unique')
    op.add_column('orders', sa.Column('pickup_point_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('service_fee', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.alter_column('orders', 'shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'pickup_points', ['pickup_point_id'], ['pickup_point_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'service_fee')
    op.drop_column('orders', 'pickup_point_id')
    op.create_unique_constraint(op.f('cart_items_user_id_part_id_key'), 'cart_items', ['user_id', 'part_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('car_orders')
    op.drop_table('settings')
    op.drop_table('pickup_points')
    # ### end Alembic commands ###
