"""Create Table Part and other for this table

Revision ID: c7839adfbee1
Revises: 
Create Date: 2025-11-20 23:01:06.574214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7839adfbee1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['part_categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('parts',
    sa.Column('part_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_name', sa.String(length=50), nullable=False),
    sa.Column('part_article', sa.String(length=70), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['part_categories.category_id'], ),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('part_specifications',
    sa.Column('spec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('spec_name', sa.String(length=50), nullable=False),
    sa.Column('spec_value', sa.String(length=100), nullable=False),
    sa.Column('spec_unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('spec_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_specifications')
    op.drop_table('parts')
    op.drop_table('part_categories')
    # ### end Alembic commands ###
