"""Car table

Revision ID: d4ceebdbb7a7
Revises: c7839adfbee1
Create Date: 2025-11-25 00:05:46.176986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ceebdbb7a7'
down_revision: Union[str, Sequence[str], None] = 'c7839adfbee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_trims',
    sa.Column('trim_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trim_name', sa.String(length=100), nullable=True),
    sa.Column('brand_name', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('engine_volume', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('engine_power', sa.Integer(), nullable=True),
    sa.Column('engine_torque', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('drive_type', sa.String(length=20), nullable=True),
    sa.Column('body_type', sa.String(length=20), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trim_id')
    )
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trim_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('production_year', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['trim_id'], ['car_trims.trim_id'], ),
    sa.PrimaryKeyConstraint('car_id'),
    sa.UniqueConstraint('vin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('car_trims')
    # ### end Alembic commands ###
