"""Add some stroke to user address

Revision ID: e8f6e34becef
Revises: aa35c0b40ccc
Create Date: 2025-12-20 23:06:59.512452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f6e34becef'
down_revision: Union[str, Sequence[str], None] = 'aa35c0b40ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_car_orders_car_id'), table_name='car_orders')
    op.drop_index(op.f('idx_car_orders_order_id'), table_name='car_orders')
    op.drop_index(op.f('idx_pickup_points_active'), table_name='pickup_points')
    op.drop_index(op.f('idx_pickup_points_city'), table_name='pickup_points')
    op.drop_index(op.f('idx_pickup_points_country'), table_name='pickup_points')
    op.drop_index(op.f('idx_pickup_points_region'), table_name='pickup_points')
    op.add_column('user_addresses', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('user_addresses', sa.Column('entrance', sa.String(length=10), nullable=True))
    op.add_column('user_addresses', sa.Column('floor', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_addresses', 'floor')
    op.drop_column('user_addresses', 'entrance')
    op.drop_column('user_addresses', 'region')
    op.create_index(op.f('idx_pickup_points_region'), 'pickup_points', ['region'], unique=False)
    op.create_index(op.f('idx_pickup_points_country'), 'pickup_points', ['country'], unique=False)
    op.create_index(op.f('idx_pickup_points_city'), 'pickup_points', ['city'], unique=False)
    op.create_index(op.f('idx_pickup_points_active'), 'pickup_points', ['is_active'], unique=False)
    op.create_index(op.f('idx_car_orders_order_id'), 'car_orders', ['order_id'], unique=False)
    op.create_index(op.f('idx_car_orders_car_id'), 'car_orders', ['car_id'], unique=False)
    # ### end Alembic commands ###
